server:
  port: 1474

spring:
        aop:
            proxy-target-class: true
        datasource:
              url: jdbc:oracle:thin:@//132.232.36.186:1521/ORCL
              driver-class-name: oracle.jdbc.driver.OracleDriver
              username: WXChat
              password: wxchat
              type: com.alibaba.druid.pool.DruidDataSource
              dbcp2:
                test-while-idle: true
                validation-query: SELECT 1 FROM DUAL
                test-on-borrow: false
                test-on-return: false

        redis:
             host: 127.0.0.1
             password: muxi
             port: 6379
             jedis:
               pool:
                 max-active: 1000
                 max-idle: 100
                 min-idle: 1
                 max-wait: -1

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.muxi.wxchat.pojo





